import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '../styles/index.scss';
import styles from './styles.module.scss';
import { GlobalNavbar } from '@/ui/GlobalNavbar/GlobalNavbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ru'>
      <body className={inter.className}>
        <div className={styles['main-layout']}>
          <GlobalNavbar />
          {children}
        </div>
      </body>
    </html>
  );
}
